-- MySQL Script generated by MySQL Workbench
-- Sat Aug 31 16:11:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Associado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Associado` (
  `MatriculaAssoc` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Data_nascimento` DATETIME NULL,
  `Telefone` INT NOT NULL,
  `Email` INT NOT NULL,
  `CPF` INT NOT NULL,
  `Tipo (titular/dependente)` VARCHAR(45) NOT NULL,
  `Data_adesao` DATETIME NOT NULL,
  `Foto` BLOB NULL,
  `Tipo (associado/dependente)` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MatriculaAssoc`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Associado_Associado1_idx` (`Tipo (associado/dependente)` ASC) VISIBLE,
  CONSTRAINT `fk_Associado_Associado1`
    FOREIGN KEY (`Tipo (associado/dependente)`)
    REFERENCES `mydb`.`Associado` (`MatriculaAssoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atestado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atestado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atestado` (
  `idAtestado` INT NOT NULL,
  `Funcionario_MatriculaFunc` INT NOT NULL,
  `Associado_MatriculaAssoc` INT NOT NULL,
  `Data_emissao` DATETIME NOT NULL,
  `Data_validade` DATETIME NOT NULL,
  PRIMARY KEY (`idAtestado`, `Associado_MatriculaAssoc`),
  INDEX `fk_Atestado_Funcionario1_idx` (`Funcionario_MatriculaFunc` ASC) VISIBLE,
  INDEX `fk_Atestado_Associado1_idx` (`Associado_MatriculaAssoc` ASC) VISIBLE,
  CONSTRAINT `fk_Atestado_Funcionario1`
    FOREIGN KEY (`Funcionario_MatriculaFunc`)
    REFERENCES `mydb`.`Funcionario` (`MatriculaFunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atestado_Associado1`
    FOREIGN KEY (`Associado_MatriculaAssoc`)
    REFERENCES `mydb`.`Associado` (`MatriculaAssoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `Nome Cargo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Salário` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contrato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` (
  `idContrato` INT NOT NULL,
  `Data_inicio` INT NULL,
  `Data_termino` INT NULL,
  `Tipo (anual/mensal)` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Associado_MatriculaAssoc` INT NOT NULL,
  `Plano_idPlano` INT NOT NULL,
  PRIMARY KEY (`idContrato`, `Associado_MatriculaAssoc`, `Plano_idPlano`),
  INDEX `fk_Contrato_Associado1_idx` (`Associado_MatriculaAssoc` ASC) VISIBLE,
  INDEX `fk_Contrato_Plano1_idx` (`Plano_idPlano` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Associado1`
    FOREIGN KEY (`Associado_MatriculaAssoc`)
    REFERENCES `mydb`.`Associado` (`MatriculaAssoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Plano1`
    FOREIGN KEY (`Plano_idPlano`)
    REFERENCES `mydb`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `IdDpto` INT NOT NULL,
  `NomeDpto` VARCHAR(45) NULL,
  PRIMARY KEY (`IdDpto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento_esta_Instalacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento_esta_Instalacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento_esta_Instalacao` (
  `Instalacao_idInstalacao` INT NOT NULL,
  `Departamento_IdDpto` INT NOT NULL,
  PRIMARY KEY (`Instalacao_idInstalacao`, `Departamento_IdDpto`),
  INDEX `fk_Instalacao_has_Departamento_Departamento1_idx` (`Departamento_IdDpto` ASC) VISIBLE,
  INDEX `fk_Instalacao_has_Departamento_Instalacao1_idx` (`Instalacao_idInstalacao` ASC) VISIBLE,
  CONSTRAINT `fk_Instalacao_has_Departamento_Instalacao1`
    FOREIGN KEY (`Instalacao_idInstalacao`)
    REFERENCES `mydb`.`Instalacao` (`idInstalacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instalacao_has_Departamento_Departamento1`
    FOREIGN KEY (`Departamento_IdDpto`)
    REFERENCES `mydb`.`Departamento` (`IdDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Tecnico_Responsavel` VARCHAR(45) NULL,
  `Esporte_idEsporte` INT NOT NULL,
  PRIMARY KEY (`idEquipe`, `Esporte_idEsporte`),
  INDEX `fk_Equipe_Esporte1_idx` (`Esporte_idEsporte` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Esporte1`
    FOREIGN KEY (`Esporte_idEsporte`)
    REFERENCES `mydb`.`Esporte` (`idEsporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe_tem_associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe_tem_associado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe_tem_associado` (
  `Equipe_idEquipe` INT NOT NULL,
  `Associado_MatriculaAssoc` INT NOT NULL,
  PRIMARY KEY (`Equipe_idEquipe`, `Associado_MatriculaAssoc`),
  INDEX `fk_Equipe_has_Associado_Associado1_idx` (`Associado_MatriculaAssoc` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Associado_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Associado_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_has_Associado_Associado1`
    FOREIGN KEY (`Associado_MatriculaAssoc`)
    REFERENCES `mydb`.`Associado` (`MatriculaAssoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Esporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Esporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Esporte` (
  `idEsporte` INT NOT NULL,
  `Nome Esporte` VARCHAR(45) NOT NULL,
  `Tipo (ind/col)` VARCHAR(45) NOT NULL,
  `Instalacao_idInstalacao` INT NOT NULL,
  PRIMARY KEY (`idEsporte`, `Instalacao_idInstalacao`),
  INDEX `fk_Esporte_Instalacao1_idx` (`Instalacao_idInstalacao` ASC) VISIBLE,
  CONSTRAINT `fk_Esporte_Instalacao1`
    FOREIGN KEY (`Instalacao_idInstalacao`)
    REFERENCES `mydb`.`Instalacao` (`idInstalacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_realizacao` DATETIME NULL,
  `Descricao` VARCHAR(45) NULL,
  `Eventocol` VARCHAR(45) NULL,
  `Associado_MatriculaAssoc` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Equipe_Esporte_idEsporte` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Associado1_idx` (`Associado_MatriculaAssoc` ASC) VISIBLE,
  INDEX `fk_Evento_Equipe1_idx` (`Equipe_idEquipe` ASC, `Equipe_Esporte_idEsporte` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Associado1`
    FOREIGN KEY (`Associado_MatriculaAssoc`)
    REFERENCES `mydb`.`Associado` (`MatriculaAssoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe` , `Equipe_Esporte_idEsporte`)
    REFERENCES `mydb`.`Equipe` (`idEquipe` , `Esporte_idEsporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `MatriculaFunc` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Data_admissao` DATETIME NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Departamento_IdDpto` INT NOT NULL,
  PRIMARY KEY (`MatriculaFunc`, `Cargo_idCargo`, `Departamento_IdDpto`),
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Funcionario_Departamento1_idx` (`Departamento_IdDpto` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Departamento1`
    FOREIGN KEY (`Departamento_IdDpto`)
    REFERENCES `mydb`.`Departamento` (`IdDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_instrui_Esporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario_instrui_Esporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_instrui_Esporte` (
  `Funcionario_MatriculaFunc` INT NOT NULL,
  `Funcionario_Cargo_idCargo` INT NOT NULL,
  `Funcionario_Departamento_IdDpto` INT NOT NULL,
  `Esporte_idEsporte` INT NOT NULL,
  `Esporte_Instalacao_idInstalacao` INT NOT NULL,
  PRIMARY KEY (`Funcionario_MatriculaFunc`, `Funcionario_Cargo_idCargo`, `Funcionario_Departamento_IdDpto`, `Esporte_idEsporte`, `Esporte_Instalacao_idInstalacao`),
  INDEX `fk_Funcionario_has_Esporte_Esporte1_idx` (`Esporte_idEsporte` ASC, `Esporte_Instalacao_idInstalacao` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Esporte_Funcionario1_idx` (`Funcionario_MatriculaFunc` ASC, `Funcionario_Cargo_idCargo` ASC, `Funcionario_Departamento_IdDpto` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_has_Esporte_Funcionario1`
    FOREIGN KEY (`Funcionario_MatriculaFunc` , `Funcionario_Cargo_idCargo` , `Funcionario_Departamento_IdDpto`)
    REFERENCES `mydb`.`Funcionario` (`MatriculaFunc` , `Cargo_idCargo` , `Departamento_IdDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Esporte_Esporte1`
    FOREIGN KEY (`Esporte_idEsporte` , `Esporte_Instalacao_idInstalacao`)
    REFERENCES `mydb`.`Esporte` (`idEsporte` , `Instalacao_idInstalacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario_treina_Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario_treina_Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario_treina_Equipe` (
  `Funcionario_MatriculaFunc` INT NOT NULL,
  `Funcionario_Cargo_idCargo` INT NOT NULL,
  `Funcionario_Departamento_IdDpto` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Equipe_Esporte_idEsporte` INT NOT NULL,
  PRIMARY KEY (`Funcionario_MatriculaFunc`, `Funcionario_Cargo_idCargo`, `Funcionario_Departamento_IdDpto`, `Equipe_idEquipe`, `Equipe_Esporte_idEsporte`),
  INDEX `fk_Funcionario_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC, `Equipe_Esporte_idEsporte` ASC) VISIBLE,
  INDEX `fk_Funcionario_has_Equipe_Funcionario1_idx` (`Funcionario_MatriculaFunc` ASC, `Funcionario_Cargo_idCargo` ASC, `Funcionario_Departamento_IdDpto` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_has_Equipe_Funcionario1`
    FOREIGN KEY (`Funcionario_MatriculaFunc` , `Funcionario_Cargo_idCargo` , `Funcionario_Departamento_IdDpto`)
    REFERENCES `mydb`.`Funcionario` (`MatriculaFunc` , `Cargo_idCargo` , `Departamento_IdDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe` , `Equipe_Esporte_idEsporte`)
    REFERENCES `mydb`.`Equipe` (`idEquipe` , `Esporte_idEsporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instalacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instalacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instalacao` (
  `idInstalacao` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Capacidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstalacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instalacao_realiza_Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instalacao_realiza_Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instalacao_realiza_Evento` (
  `Instalacao_idInstalacao` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`Instalacao_idInstalacao`, `Evento_idEvento`),
  INDEX `fk_Instalacao_has_Evento_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_Instalacao_has_Evento_Instalacao1_idx` (`Instalacao_idInstalacao` ASC) VISIBLE,
  CONSTRAINT `fk_Instalacao_has_Evento_Instalacao1`
    FOREIGN KEY (`Instalacao_idInstalacao`)
    REFERENCES `mydb`.`Instalacao` (`idInstalacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Instalacao_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `Data_pagamento` DATETIME NULL,
  `Valor` DECIMAL(10,2) NULL,
  `Metodo` VARCHAR(45) NULL,
  `Status (pago/nao_pago)` VARCHAR(45) NULL,
  `Contrato_idContrato` INT NOT NULL,
  `Contrato_Associado_MatriculaAssoc` INT NOT NULL,
  `Contrato_Plano_idPlano` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Contrato_idContrato`, `Contrato_Associado_MatriculaAssoc`, `Contrato_Plano_idPlano`),
  INDEX `fk_Pagamento_Contrato1_idx` (`Contrato_idContrato` ASC, `Contrato_Associado_MatriculaAssoc` ASC, `Contrato_Plano_idPlano` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Contrato1`
    FOREIGN KEY (`Contrato_idContrato` , `Contrato_Associado_MatriculaAssoc` , `Contrato_Plano_idPlano`)
    REFERENCES `mydb`.`Contrato` (`idContrato` , `Associado_MatriculaAssoc` , `Plano_idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Plano` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Plano` (
  `idPlano` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  `Periodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlano`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
